# Generated by Django 3.0.3 on 2020-08-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('tag', models.CharField(choices=[('Shirts', 'Shirts'), ('Dresses', 'Dresses'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Gymwear', 'Gymwear'), ('Shoes', 'Shoes')], default='Jeans', max_length=10)),
            ],
        ),
    ]
